export default {
  ENV: process.env.EXPO_PUBLIC_ENV,
  APP_URL: process.env.EXPO_PUBLIC_APP_URL,
  API_URL: process.env.EXPO_PUBLIC_API_URL,
  API_KEY: process.env.EXPO_PUBLIC_API_KEY,
  GOOGLE_CLIENT_ID: process.env.EXPO_PUBLIC_GOOGLE_CLIENT_ID,
  FACEBOOK_APP_ID: process.env.EXPO_PUBLIC_FACEBOOK_APP_ID,

  FIREBASE_API_KEY: process.env.EXPO_PUBLIC_FIREBASE_CLIENT_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.EXPO_PUBLIC_FIREBASE_APP_ID,

  ALGOLIA_SEARCH: {
    APP_ID: process.env.EXPO_PUBLIC_ALGOLIA_APP_ID || "",
    PUBLIC_API_KEY: process.env.EXPO_PUBLIC_ALGOLIA_PUBLIC_API_KEY || "",
    CONNECT_INDEX: process.env.EXPO_PUBLIC_ALGOLIA_CONNECT_INDEX || "",
    SITE_WIDE_INDEX: process.env.EXPO_PUBLIC_ALGOLIA_SITE_WIDE_INDEX || "",
  },
};
